In [1]:
# Import required libraries
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt
import sklearn
from sklearn.neural_network import MLPClassifier
from sklearn.neural_network import MLPRegressor

# Import necessary modules
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from math import sqrt
from sklearn.metrics import r2_score

In [2]:
from google.colab import files
data_to_load = files.upload()

Saving ds.csv to ds.csv


In [3]:
import io
df = pd.read_csv(io.BytesIO(data_to_load['ds.csv']))
df.head(20)

Year  Month   Temp 0C  Rainfall (mm)  Humidity (%)  Dengue Victims
0   2016      1        27          33.74            74            2184
1   2016      2        28          33.92            73            1569
2   2016      3        28          41.27            74            1016
3   2016      4        29         101.74            77             942
4   2016      5        28         655.50            83             693
5   2016      6        27         351.98            86            1459
6   2016      7        27         191.54            85            3191
7   2016      8        27         201.60            85            1478
8   2016      9        26          88.61            85             939
9   2016     10        27          55.06            79             459
10  2016     11        27         112.16            79             460
11  2016     12        26          55.57            76            2377
12  2017      1        26          43.68            72            2734
13  2017      2        26          15.36            73            1900
14  2017      3        27          98.07            77            2467
15  2017      4        28          74.51            79            2570
16  2017      5        28         332.59            82            3333
17  2017      6        27         266.42            86            5372
18  2017      7        27         209.89            84            7471
19  2017      8        27         330.75            85            3620

In [4]:
print(df.shape)
df.describe().transpose()

(48, 6)


count         mean          std  ...       50%       75%     max
Year             48.0  2017.500000     1.129865  ...  2017.500  2018.250  2019.0
Month            48.0     6.500000     3.488583  ...     6.500     9.250    12.0
 Temp 0C         48.0    27.375000     0.959277  ...    27.000    28.000    30.0
Rainfall (mm)    48.0   269.475625   234.719722  ...   197.795   358.275   954.0
Humidity (%)     48.0    80.604167     3.818987  ...    81.000    84.000    86.0
Dengue Victims   48.0  1708.687500  1384.485543  ...  1271.500  2232.250  7471.0

[6 rows x 8 columns]

In [5]:
target_column = ['Dengue Victims'] 
predictors = list(set(list(df.columns))-set(target_column))
df[predictors] = df[predictors]/df[predictors].max()
df.describe().transpose()

count         mean  ...          75%     max
Year             48.0     0.999257  ...     0.999629     1.0
Month            48.0     0.541667  ...     0.770833     1.0
 Temp 0C         48.0     0.912500  ...     0.933333     1.0
Rainfall (mm)    48.0     0.282469  ...     0.375550     1.0
Humidity (%)     48.0     0.937258  ...     0.976744     1.0
Dengue Victims   48.0  1708.687500  ...  2232.250000  7471.0

[6 rows x 8 columns]

In [6]:
X = df[predictors].values
y = df[target_column].values

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=40)
print(X_train.shape); print(X_test.shape)

(33, 5)
(15, 5)


In [7]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(8,8,8), activation='relu', solver='adam', max_iter=1000)
mlp.fit(X_train,y_train)

predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:934: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.7/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:571: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  % self.max_iter, ConvergenceWarning)


In [8]:
from sklearn.metrics import classification_report,confusion_matrix
print(confusion_matrix(y_train,predict_train))
print(classification_report(y_train,predict_train))

[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 1]]
              precision    recall  f1-score   support

         387       0.00      0.00      0.00         1
         403       1.00      1.00      1.00         1
         459       1.00      1.00      1.00         1
         460       1.00      1.00      1.00         1
         579       1.00      1.00      1.00         1
         622       1.00      1.00      1.00         1
         792       1.00      1.00      1.00         1
         815       1.00      1.00      1.00         1
         866       1.00      1.00      1.00         1
         939       0.50      1.00      0.67         1
         942       0.00      0.00      0.00         1
         977       0.50      1.00      0.67         1
        1037       1.00      1.00      1.00         1
        1126       1.00      1.00      1.00         1
        1131       0.00      0.00      0.00         1
        1251   

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
